### ISSUE TITLE
Missing .defaultCellUpdate

### ISSUE THREAD

**Issue by sedwo** [EurekaCommunity/FloatLabelRow#13]
Trying to set defaults like:
```
LabelRow.defaultCellUpdate = { cell, row in
    cell.contentView.backgroundColor = .red
    cell.textLabel?.textColor = .white
    cell.textLabel?.font = UIFont.boldSystemFont(ofSize: 13)
    cell.textLabel?.textAlignment = .right
}
```

Receive an error using:
```
FloatLabelRow.defaultCellUpdate = { cell, row in
}
```
![image](https://user-images.githubusercontent.com/1434449/36826399-ffea382e-1cda-11e8-8bb3-41290258ea1d.png)

**Comment by mats-claassen** [comment]
`FloatLabelRow` is generic so that you would have to set it like:

```swift
NameFloatLabelRow.defaultCellUpdate = { cell, row in
}
``` 

or whatever subclass of `FloatLabelRow` you use. If you use several of them and want to perform the exact same actions on them consider putting them in an Array and then setting `defaultCellUpdate` inside a map or loop.
