### ISSUE TITLE
[!] Unable to find a specification for `FloatLabelRow`

### ISSUE THREAD

**Issue by Sweeper777** [EurekaCommunity/FloatLabelRow#2]
I added this to my Podfile:

    pod 'FloatLabelRow'

When I do `pod install`, the error says:

    [!] Unable to find a specification for `FloatLabelRow`

I also tried these:

    pod 'FloatLabelRow', '~> 1.0'
    pod 'FloatLabelRow', '~> 1.0.0'

but the same error occurs on `pod install`.

**Comment by KarinaFernandez** [comment]
Hi @Sweeper777!
Thanks for your interest in used FloatLabelRow. 
It wasn't able to be used with cocoapods when you asked, but now it's possible!

Just ensure to run 
```swift
pod repo update
pod install
```
Sorry for the delay!

**Comment by Sweeper777** [comment]
I still can't install it though... The same error still appears. I can't even find it on cocoa pods.org.

**Comment by KarinaFernandez** [comment]
Hi @Sweeper777 
Sorry for the inconvenience!
I think that cocoapods wasn't working very well some days ago, but now it appears (https://cocoapods.org/?q=floatlabelrow).

Anyway if you continue with this issue, could you please send me your podfile?

**Comment by Sweeper777** [comment]
I have successfully installed it! 😄 At the time of your comment, I did see it on cocoapods.org, but when I checked today, it's not there anymore!
